//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category_Question
    {
        public int category_question_id { get; set; }
        public int questionId { get; set; }
        public int categoryId { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Question Question { get; set; }
    }
}
